# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 02:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('state', models.TextField(default='created')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('bus_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bus_app.Bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='trips',
            field=models.ManyToManyField(blank=True, null=True, to='bus_app.Trip'),
        ),
    ]
