# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='position',
            field=models.TextField(default='{"lat": 47.22751, "bus_id": 1337, "long": 39.71083}'),
            preserve_default=False,
        ),
    ]
